import type { AssistantContext } from "./types";
import { getCategory } from "@/lib/data/categories";
import { getGoal } from "@/lib/data/goals";
import { compareCallouts } from "@/lib/data/compare-insights";
import { linkBetween } from "@/lib/data/compatibility";
import type { HardwareProduct } from "@/lib/data/types";

/**
 * Turns an AssistantContext into a compact, structured block of *real* facts
 * — the only material a live model is allowed to treat as ground truth about
 * HardwareNeeds' catalog, current build, or compatibility rules. Nothing
 * here is generated by a model; it's a direct, deterministic read of
 * src/lib/data/*. This is the "provide structured facts to the AI" step of
 * the pipeline described in the product spec.
 */

function specLines(product: HardwareProduct): string {
  return product.specs.map((s) => `  - ${s.label}: ${s.value}`).join("\n");
}

function productBlock(product: HardwareProduct, label: string): string {
  const category = getCategory(product.categoryId);
  return [
    `${label}: ${product.brand} ${product.name} (${category?.name ?? product.categoryId}, ${product.tier} tier)`,
    `  Price: $${product.priceUSD.toLocaleString("en-US")} (estimated, not live pricing)`,
    `  Summary: ${product.summary}`,
    `  Specs:`,
    specLines(product),
    `  Strengths: ${product.strengths.join("; ") || "none on file"}`,
    `  Limitations: ${product.considerations.join("; ") || "none on file"}`,
    `  Best for: ${product.useCases?.join(", ") || "not tagged"}`,
    `  Upgradeability: ${product.upgradeNote ?? "no upgrade note on file"}`,
    typeof product.powerConsumptionW === "number" ? `  Rated power draw: ${product.powerConsumptionW} W` : undefined,
  ]
    .filter(Boolean)
    .join("\n");
}

function answersLine(answers: Record<string, string | string[] | number>): string {
  const entries = Object.entries(answers).filter(([, v]) => v !== undefined && v !== "");
  if (entries.length === 0) return "  (no specific answers recorded yet)";
  return entries.map(([k, v]) => `  - ${k}: ${Array.isArray(v) ? v.join(", ") : v}`).join("\n");
}

export function buildFacts(context: AssistantContext): string {
  switch (context.kind) {
    case "product": {
      return `HARDWARENEEDS CATALOG ENTRY BEING VIEWED\n${productBlock(context.product, "Product")}`;
    }

    case "plan": {
      const goal = getGoal(context.goalId);
      const total = context.recommendations.reduce((sum, r) => sum + r.product.priceUSD, 0);
      const parts = context.recommendations
        .map((r) => {
          const category = getCategory(r.categoryId);
          const score = r.score
            ? Object.entries(r.score)
                .filter(([, v]) => typeof v === "number")
                .map(([k, v]) => `${k}=${v}`)
                .join(", ")
            : "not scored";
          return [
            `- ${category?.name ?? r.categoryId}: ${r.product.brand} ${r.product.name} — $${r.product.priceUSD.toLocaleString("en-US")}`,
            `  Role: ${r.role}`,
            `  Why picked: ${r.reasoning.join(" ")}`,
            r.whyNotAlternative ? `  Why not the alternative: ${r.whyNotAlternative}` : undefined,
            `  Heuristic scores (0-100, not lab-measured): ${score}`,
          ]
            .filter(Boolean)
            .join("\n");
        })
        .join("\n");
      return [
        `CURRENT PLAN — goal: ${goal?.label ?? context.goalId}${goal ? ` (${goal.description})` : ""}`,
        `User's answers so far:\n${answersLine(context.answers)}`,
        `Recommended build (real catalog picks, already compatibility-checked):`,
        parts || "  (no recommendation generated yet)",
        `Estimated total: $${total.toLocaleString("en-US")}`,
      ].join("\n\n");
    }

    case "compare": {
      const category = getCategory(context.categoryId);
      const callouts = compareCallouts(context.productA, context.productB, context.categoryId);
      const calloutLines = callouts
        .map((c) => `  - ${c.label}: ${c.winner === "a" ? context.productA.name : context.productB.name}`)
        .join("\n");
      return [
        `COMPARING TWO ${category?.name?.toUpperCase() ?? context.categoryId} OPTIONS`,
        productBlock(context.productA, "Option A"),
        productBlock(context.productB, "Option B"),
        `Pre-computed differences (derived from real specs):\n${calloutLines || "  (no meaningful differences detected)"}`,
      ].join("\n\n");
    }

    case "compatibility": {
      const categoryA = getCategory(context.categoryAId);
      const categoryB = getCategory(context.categoryBId);
      const link = linkBetween(context.categoryAId, context.categoryBId);
      const lines = [
        `CHECKING COMPATIBILITY: ${categoryA?.name ?? context.categoryAId} <-> ${categoryB?.name ?? context.categoryBId}`,
        link
          ? `Known relationship: "${link.label}" (${link.kind} — ${link.kind === "critical" ? "hard requirement" : link.kind === "physical" ? "physical clearance requirement" : "affects value, not a blocker"}). ${link.detail}`
          : "No specific compatibility rule is on file between these two categories.",
      ];
      if (context.productA) lines.push(productBlock(context.productA, `Selected ${categoryA?.name ?? "A"}`));
      if (context.productB) lines.push(productBlock(context.productB, `Selected ${categoryB?.name ?? "B"}`));
      return lines.join("\n\n");
    }

    case "general":
    default:
      return "No specific product, build, or comparison is currently open. Answer generally, or point the user to Plan/Hardware/Compare to get grounded, specific help.";
  }
}
